#
# ~/.bash_profile
#

source ~/.secrets.sh

export EDITOR="vim"
export BROWSER="iridium-browser"
export VENV_DIR="/home/benv/.venv"

[[ -f ~/.bashrc ]] && . ~/.bashrc

if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
  exec startx
fi
