#
# ~/.bash_profile
#

source ~/.secrets.sh

export EDITOR="vim"
export BROWSER="firefox"
export VENV_DIR="/home/benv/.venv"
export BATTERY_NAME="BAT0"
export AC_ADAPTER_NAME="AC"

[[ -f ~/.bashrc ]] && . ~/.bashrc

if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
  exec startx
fi
