syntax on

" Copy and paste
vnoremap <C-c> "+y
map <C-v> "+P

" Quick save and exit
map <C-e> :wq<CR> 
imap <C-e> <Esc>:wq<CR>

" Save files as sudo without doing 'sudo vim'
cmap w!! w !sudo tee > /dev/null %

" Set cursor styles
let &t_SI .= "\<Esc>[6 q"
let &t_EI .= "\<Esc>[2 q"
autocmd VimLeave * silent !echo -ne "\e[6 q"

" Allow mouse scrolling
set mouse=a

au FileType gitcommit setlocal tw=72
au FileType *.md setlocal tw=80

autocmd BufWritePost */i3/config !i3-msg reload
autocmd BufWritePost */i3blocks/config !i3-msg reload
autocmd BufWritePost *sxhkdrc !pkill -USR1 sxhkd
autocmd BufWritePost /home/benv/scripts/* !chmod +x /home/benv/scripts/*
autocmd BufWritePost /home/benv/.Xresources !xrdb -merge </home/benv/.Xresources
autocmd BufWritePost */termite/config !killall -USR1 termite
