syntax on

" Copy and paste
vnoremap <C-c> "+y
map <C-v> "+P

" Quick save and exit
map <C-e> :wq<CR> 
imap <C-e> <Esc>:wq<CR>

" Disable macro recording
map q <Nop>

" Save files as sudo without doing 'sudo vim'
cmap w!! w !sudo tee > /dev/null %

" Set cursor styles
let &t_SI .= "\<Esc>[6 q"
let &t_EI .= "\<Esc>[2 q"
autocmd VimLeave * silent !echo -ne "\e[6 q"

" Allow mouse scrolling
set mouse=a

" For alacritty compatibility
set ttymouse=sgr

set scrolloff=8
set sidescrolloff=8

" Move lines
nnoremap <C-j> :m .+1<CR>==
nnoremap <C-k> :m .-2<CR>==
inoremap <C-j> <Esc>:m .+1<CR>==gi
inoremap <C-k> <Esc>:m .-2<CR>==gi
vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv

au FileType gitcommit setlocal tw=72
au FileType *.md setlocal tw=80

autocmd BufWritePost */i3/config !i3-msg reload
autocmd BufWritePost */i3blocks/config !i3-msg reload
autocmd BufWritePost *sxhkdrc !pkill -USR1 sxhkd
autocmd BufWritePost /home/benv/scripts/* !chmod +x /home/benv/scripts/*
autocmd BufWritePost /home/benv/.Xresources !xrdb -merge </home/benv/.Xresources
