#!/bin/sh

export PATH="$HOME/scripts:$HOME/.local/bin:$PATH"

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Pick a random wallpaper and colourscheme
wal -i ~/images

# Start ssh-agent
eval $(ssh-agent)

eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

# Start 'xautolock'. Lock screen after 5 minutes unless mouse is within 50px of any corner
xautolock -time 2 -corners "----" -cornersize 50 -locker lock &

# Reset touchscreen output
xinput --map-to-output 'ELAN Touchscreen' eDP1

# Start hotkey daemon
sxhkd &

setxkbmap -layout gb
xrdb -merge ~/.Xresources
compton & -b -d :0 &
exec i3

