#!/bin/bash
BACKGROUND=$(xgetres i3wm.color1 || echo "#f0f0f0")
FOREGROUND=$(xgetres i3wm.color2 || echo "f4f4f4")
NB="-nb '$BACKGROUND'"
SB="-sb '$FOREGROUND'" 
DMENU="dmenu -i -nf '#ffffff' -sf '#ffffff' $NB $SB"
echo "$DMENU"
j4-dmenu-desktop --dmenu="$DMENU"
