#!/bin/bash
BACKGROUND=$(xgetres i3wm.color1 || echo "#0f0f0f")
FOREGROUND=$(xgetres i3wm.color2 || echo "#999999")
/usr/bin/dmenu -i -nf '#ffffff' -sf '#ffffff' -nb "$BACKGROUND" -sb "$FOREGROUND" "$@"
