#!/bin/sh

term () {
    i3-msg exec "termite -e /bin/bash"
}

i3-msg workspace "1"
i3-msg exec "spotify --force-device-scale-factor=1.75 %U"
sleep 5

i3-msg workspace "2"
sleep 1
i3-msg move workspace to output left
sleep 1
i3-msg exec "/bin/bash -c '/opt/wavebox.io/wavebox/wavebox-launcher '"
sleep 5

i3-msg workspace "3"
sleep 1
i3-msg move workspace to output left
sleep 1
i3-msg exec "$BROWSER" 
sleep 5

i3-msg workspace "4"
sleep 1
i3-msg move workspace to output left
term
term

i3-msg workspace "5"
sleep 1
i3-msg exec pycharm
sleep 10

i3-msg exec pcmanfm
sleep 0.5
i3-msg move scratchpad
sleep 0.5
term
sleep 1
archey3
sleep 0.5
i3-msg move scratchpad
i3-msg workspace "1"
