config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_git-templates:
    dst: ~/.git-templates
    src: git-templates
  d_scripts:
    dst: ~/scripts
    src: scripts
  f_bash_profile:
    dst: ~/.bash_profile
    src: bash_profile
  f_bashrc:
    dst: ~/.bashrc
    src: bashrc
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_npmrc:
    src: npmrc
    dst: ~/.npmrc
  d_gtk-3.0:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
  f_gtkrc-2.0:
    src: gtkrc-2.0
    dst: ~/.gtkrc-2.0
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  f_inputrc:
    src: inputrc
    dst: ~/.inputrc
  f_spotify-flags.conf:
    src: config/spotify-flags.conf
    dst: ~/.config/spotify-flags.conf
  f_config:
    src: config/sway/config
    dst: ~/.config/sway/config
profiles:
  mu:
    dotfiles:
    - ALL
