config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_by_default: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_applications:
    dst: ~/.local/share/applications
    src: local/share/applications
  d_git-templates:
    dst: ~/.git-templates
    src: git-templates
  f_70-synaptics.conf:
    dst: /etc/X11/xorg.conf.d/70-synaptics.conf
    src: etc/X11/xorg.conf.d/70-synaptics.conf
  f_bash_profile:
    dst: ~/.bash_profile
    src: bash_profile
  f_bashrc:
    dst: ~/.bashrc
    src: bashrc
  f_config:
    dst: ~/.config/i3/config
    src: config/i3/config
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_i3status_config:
    dst: ~/.config/i3status/config
    src: config/i3status/config
  f_local.conf:
    dst: /etc/fonts/local.conf
    src: etc/fonts/local.conf
  f_new-workspace:
    dst: ~/.config/i3/new-workspace
    src: config/i3/new-workspace
  f_vconsole.conf:
    dst: /etc/vconsole.conf
    src: etc/vconsole.conf
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_xbindkeysrc:
    dst: ~/.xbindkeysrc
    src: xbindkeysrc
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xrandr-extend.cfg:
    dst: ~/.config/xrandr-extend.cfg
    src: config/xrandr-extend.cfg
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
profiles:
  omega:
    dotfiles:
    - f_bashrc
    - f_bash_profile
    - f_vimrc
    - f_xbindkeysrc
    - f_xinitrc
    - f_xresources
    - f_config
    - f_i3status_config
    - f_local.conf
    - f_xrandr-extend.cfg
    - d_applications
    - f_new-workspace
    - d_git-templates
    - f_gitconfig
    - f_70-synaptics.conf
    - f_vconsole.conf
